version: '3.6'

services:
  spark:
    container_name: spark
    image: docker.io/bitnami/spark:3.2.0
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no     
      - INIT_DAEMON_STEP=setup_spark
    ports:
      - '8080:8080'
      - '7077:7077'
    networks:
      - deltalake
    depends_on:
      - postgres
  spark-worker:
    build:
      context: ./spark-worker
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - deltalake
    depends_on:
      - spark 
  spark-submit:
      build:  
        context: ./test-spark-submit
        dockerfile: Dockerfile
        args: 
          AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
          AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      container_name: spark-submit
      environment:
          - ENABLE_INIT_DAEMON=false
          - PYSPARK_PYTHON=python3
      image: spark-app
      depends_on:
        - spark-worker   
      networks:
        - deltalake  
      volumes:
      - $PWD:/app 
networks:
    deltalake: 
      driver: bridge  
    