image_name := 'delta-lake'
postgres_user := 'postgres'
postgres_password := 'postgres'
postgres_host := 'host.docker.internal'
postgres_port := '5432'
postgres_db_name := 'police-data'
table_name := 'test'

build:
    docker build -t {{image_name}} .

run:
    docker run --mount type=bind,source="$(pwd)",target=/opt/application \
        -e POSTGRES_USER={{postgres_user}} -e POSTGRES_PASSWORD={{postgres_password}} -e POSTGRES_HOST={{postgres_host}} \
        -e POSTGRES_PORT={{postgres_port}} -e POSTGRES_DB_NAME={{postgres_db_name}} -e TABLE_NAME={{table_name}} \
        {{image_name}} driver local:///opt/application/main.py \
        --add-host=host.docker.internal:host-gateway

shell:
    docker run -it \
    {{image_name}} /opt/spark/bin/pyspark --packages com.amazonaws:aws-java-sdk-bundle:1.11.375,org.apache.hadoop:hadoop-aws:3.2.0